const tableItems = [
  {
    id: 0,
    position: "Backend Engineer",
    company: "Verily",
    location: "Tel-Aviv",
    dateCreated: (new Date(2018, 11, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2018, 11, 25, 10, 33, 30, 0)).toLocaleString(),
    status: "Applied",
    actions: ":",
  },
  {
    id: 1,
    position: "Fullstack Engineer",
    company: "Google",
    location: "Tel-Aviv",
    dateCreated: (new Date(2018, 10, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2018, 10, 30, 10, 33, 30, 0)).toLocaleString(),
    status: "Wish List",
    actions: ":",
  },
  {
    id: 2,
    position: "Software Engineer",
    company: "Taboola",
    location: "Tel-Aviv",
    dateCreated: (new Date(2019, 6, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2019, 10, 30, 10, 33, 30, 0)).toLocaleString(),
    status: "Interview",
    actions: ":",
  },
  {
    id: 3,
    position: "Backend Engineer",
    company: "Wix",
    location: "Herzliya",
    dateCreated: (new Date(2019, 8, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2019, 9, 25, 10, 33, 30, 0)).toLocaleString(),
    status: "Applied",
    actions: ":",
  },
  {
    id: 4,
    position: "Fullstack Engineer",
    company: "Google",
    location: "Tel-Aviv",
    dateCreated: (new Date(2018, 3, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2018, 3, 24, 10, 33, 30, 0)).toLocaleString(),
    status: "Wish List",
    actions: ":",
  },
  {
    id: 5,
    position: "Software Engineer",
    company: "Check Point",
    location: "Tel-Aviv",
    dateCreated: (new Date(2020, 6, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2020, 9, 30, 10, 33, 30, 0)).toLocaleString(),
    status: "Interview",
    actions: ":",
  },
  {
    id: 6,
    position: "Fullstack Engineer",
    company: "Elbit",
    location: "Holon",
    dateCreated: (new Date(2018, 9, 24, 8, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2018, 10, 30, 13, 33, 30, 0)).toLocaleString(),
    status: "Wish List",
    actions: ":",
  },
  {
    id: 7,
    position: "Software Engineer",
    company: "IronSource",
    location: "Tel-Aviv",
    dateCreated: (new Date(2020, 6, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2020, 10, 30, 10, 33, 30, 0)).toLocaleString(),
    status: "Terminated",
    actions: ":",
  },
  {
    id: 8,
    position: "Fullstack Engineer",
    company: "Wix",
    location: "Herzliya",
    dateCreated: (new Date(2019, 8, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2019, 9, 25, 10, 33, 30, 0)).toLocaleString(),
    status: "Applied",
    actions: ":",
  },
  {
    id: 9,
    position: "Software Engineer",
    company: "Verily",
    location: "Tel-Aviv",
    dateCreated: (new Date(2018, 4, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2018, 4, 24, 10, 33, 30, 0)).toLocaleString(),
    status: "Wish List",
    actions: ":",
  },
  {
    id: 10,
    position: "Sofware Developer",
    company: "Check Point",
    location: "Tel-Aviv",
    dateCreated: (new Date(2020, 6, 24, 10, 33, 30, 0)).toLocaleString(),
    lastModified: (new Date(2020, 9, 30, 10, 33, 30, 0)).toLocaleString(),
    status: "Interview",
    actions: ":",
  },
];



export default tableItems;
